import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  Modal,
  TouchableOpacity,
  ScrollView,
  Linking,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing, radii, typography, minTouchTarget } from '../theme/tokens';

const PRIVACY_POLICY_URL = 'https://www.menolisa.com/privacy';
const OPENAI_PRIVACY_URL = 'https://openai.com/policies/privacy-policy';

type Props = {
  visible: boolean;
  onAccept: () => void;
};

export function MedicalDisclaimerModal({ visible, onAccept }: Props) {
  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      statusBarTranslucent
    >
      <View style={styles.overlay}>
        <View style={styles.card}>
          <View style={styles.iconWrap}>
            <Ionicons name="shield-checkmark" size={28} color={colors.primary} />
          </View>
          <Text style={styles.title}>Before you begin</Text>

          <ScrollView
            style={styles.scroll}
            contentContainerStyle={styles.scrollContent}
            showsVerticalScrollIndicator={false}
          >
            {/* Medical disclaimer */}
            <View style={styles.section}>
              <Ionicons name="medkit-outline" size={18} color={colors.textMuted} style={styles.sectionIcon} />
              <Text style={styles.sectionTitle}>Not medical advice</Text>
              <Text style={styles.sectionBody}>
                MenoLisa provides wellness information only. It is not a substitute for professional
                medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider
                before making any health decisions.
              </Text>
              <Text style={styles.sectionBody}>
                Your 8-week plan is built from your quiz answers —{' '}
                <Text style={styles.bold}>not from a medical assessment</Text>. Lisa&apos;s answers are
                generated by AI and can be incomplete or wrong, so please don&apos;t rely on them as
                your only source of health information.
              </Text>
            </View>

            {/* Exercise safety.
                The plan prescribes real movement — loaded strength work, plyometric
                bone loading and, from week 3, all-out intervals — and nothing in the
                funnel screens her for any of it: the limitations question was removed
                and safety_flags is empty for every web signup. The plan itself ramps
                impact and intensity over the first two weeks, but a ramp is not a
                screen. This section is the only place she is told what the product
                cannot know about her, so it says it before she starts rather than in
                the Terms page she agreed to before she had seen an exercise. */}
            <View style={styles.section}>
              <Ionicons name="fitness-outline" size={18} color={colors.textMuted} style={styles.sectionIcon} />
              <Text style={styles.sectionTitle}>Before you start moving</Text>
              <Text style={styles.sectionBody}>
                Check with your doctor first if you are pregnant, recovering from surgery or an
                injury, living with a heart, bone or joint condition, or taking medication that
                affects how you exercise.
              </Text>
              <Text style={styles.sectionBody}>
                Stop and get it looked at if a movement causes{' '}
                <Text style={styles.bold}>pain, dizziness or chest discomfort</Text>. Work around it,
                never through it — you can skip or swap anything in your plan.
              </Text>
            </View>

            {/* AI data sharing */}
            <View style={styles.section}>
              <Ionicons name="sparkles-outline" size={18} color={colors.textMuted} style={styles.sectionIcon} />
              <Text style={styles.sectionTitle}>AI & data sharing</Text>
              <Text style={styles.sectionBody}>
                To power your personalised conversations and health insights, MenoLisa sends the
                following information to <Text style={styles.bold}>OpenAI</Text> (an AI service
                provider):
              </Text>
              <View style={styles.bulletList}>
                <Text style={styles.bullet}>• Your chat messages</Text>
                <Text style={styles.bullet}>• Your symptom logs</Text>
                <Text style={styles.bullet}>• Basic health profile (age range, menopause stage, goals)</Text>
              </View>
              <Text style={styles.sectionBody}>
                This data is used solely to generate AI responses and health summaries. It is not
                sold to third parties.{' '}
                <Text
                  style={styles.link}
                  onPress={() => Linking.openURL(OPENAI_PRIVACY_URL)}
                  accessibilityRole="link"
                >
                  OpenAI Privacy Policy
                </Text>
                .
              </Text>
            </View>

            <TouchableOpacity
              onPress={() => Linking.openURL(PRIVACY_POLICY_URL)}
              accessibilityRole="link"
              style={styles.privacyLink}
            >
              <Text style={styles.link}>View MenoLisa Privacy Policy</Text>
            </TouchableOpacity>
          </ScrollView>

          <TouchableOpacity
            activeOpacity={0.85}
            style={styles.primaryButton}
            onPress={onAccept}
            accessibilityRole="button"
            accessibilityLabel="I agree and continue"
          >
            <Text style={styles.primaryButtonText}>I agree and continue</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  card: {
    backgroundColor: colors.background,
    borderRadius: radii.xl,
    padding: spacing.xl,
    width: '100%',
    maxWidth: 360,
    maxHeight: '85%',
  },
  iconWrap: {
    alignSelf: 'center',
    marginBottom: spacing.sm,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.rowBlueBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    ...typography.presets.heading2,
    color: colors.text,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  scroll: {
    flexGrow: 0,
    maxHeight: 340,
  },
  scrollContent: {
    gap: spacing.md,
    paddingBottom: spacing.md,
  },
  section: {
    backgroundColor: colors.card,
    borderRadius: radii.md,
    padding: spacing.md,
    gap: spacing.xs,
  },
  sectionIcon: {
    marginBottom: spacing.xs,
  },
  sectionTitle: {
    ...typography.presets.bodyMedium,
    color: colors.text,
  },
  sectionBody: {
    ...typography.presets.bodySmall,
    color: colors.textMuted,
    lineHeight: 20,
  },
  bulletList: {
    gap: 2,
    paddingLeft: spacing.xs,
  },
  bullet: {
    ...typography.presets.bodySmall,
    color: colors.textMuted,
    lineHeight: 20,
  },
  bold: {
    fontFamily: typography.family.semibold,
    color: colors.text,
  },
  link: {
    color: colors.primary,
    fontFamily: typography.family.semibold,
    fontSize: 13,
  },
  privacyLink: {
    alignSelf: 'center',
    paddingVertical: spacing.xs,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    minHeight: minTouchTarget,
    borderRadius: radii.lg,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.md,
  },
  primaryButtonText: {
    ...typography.presets.button,
    color: colors.background,
  },
});
